workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_pro_xcode_12
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - ifconfig | grep 10.
      - xcodebuild build -project ios-test2/banaan.xcodeproj -scheme "banaan" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - /tmp/xcodebuild_logs/*.log
