workflows:
  build-app:
    name: Build App
    max_build_duration: 10
    triggering:
      events:
        - push
    when:
      changeset:
        includes:
          - '.'
        excludes:
          - '**/*.md'
    environment:
      xcode: 12.3
      cocoapods: default
    scripts:
      - echo 42
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
